export const ROUTES = {
  ROOT: '/',
  LOGIN: '/login',
  DASHBOARD: '/dashboard',
  REGISTER: '/register',
  PRODUCTS_RETRIEVE: '/dashboard/products/retrieve',
  PRODUCTS_REGISTER: '/dashboard/products/register',
  PRODUCT_DETAIL: (id: number | string) => `/dashboard/products/${id}`,
  PRODUCT_EDIT: (id: number | string) => `/dashboard/products/${id}?mode=edit`,
  STOCK_IN_OUT: '/dashboard/stock/in-out',
  STOCK_OUTBOUND: '/dashboard/stock/outbound',
  STOCK_SEARCH: '/dashboard/stock/search',
  USER_REGISTER: '/dashboard/users/register',
  USER_MANAGE: '/dashboard/users/manage',
  COSTS_CARRIER: '/dashboard/costs/carrier',
  COSTS_CARRIER_COMPANY: '/dashboard/costs/carrier-company',
  COSTS_PACKAGE: '/dashboard/costs/package',
  COSTS_CATEGORY: '/dashboard/costs/category',
  COSTS_COMMISSION_RATE: '/dashboard/costs/commission-rate',
  SALES_PRODUCTS_RETRIEVE: '/dashboard/sales-products/retrieve' as const,
  SALES_PRODUCTS_RETRIEVE_DETAILS: (id: number | string) => `/dashboard/sales-products/retrieve/${id}` as const,
  SALES_PRODUCTS_RETRIEVE_EDIT: (id: number | string) => `/dashboard/sales-products/retrieve/${id}/edit` as const,
  MASTER_PRODUCTS: '/dashboard/master-products' as const,
  MASTER_PRODUCT_DETAIL: (id: number | string) => `/dashboard/master-products/${id}` as const,
  MASTER_PRODUCT_DETAIL_EDIT: (masterId: number | string, listingId: number | string) =>
    `/dashboard/master-products/${masterId}/detail/${listingId}` as const,
  MARGIN_POLICIES: '/dashboard/margin-policies' as const,
  LISTINGS_SYNC: '/dashboard/listings/sync' as const,
  SELLERS_LIST: '/dashboard/sellers/list' as const,
  SELLERS_MANAGE: '/dashboard/sellers/manage' as const,
  ORDERS_RETRIEVE: '/dashboard/orders' as const,
  ORDERS_SHIPMENT: '/dashboard/orders/shipment' as const,
  ORDERS_CLAIMS: '/dashboard/orders/claims' as const,
  ORDERS_INQUIRIES: '/dashboard/orders/inquiries' as const,
  PURCHASE_LIST: '/dashboard/purchase/list' as const,
  SETTINGS_LOGGING: '/dashboard/settings/logging' as const,
  THUMBNAIL_TEMPLATES: '/dashboard/thumbnail-templates' as const,
  THUMBNAIL_TEMPLATE_NEW: '/dashboard/thumbnail-templates/new' as const,
  THUMBNAIL_TEMPLATE_EDIT: (id: number | string) => `/dashboard/thumbnail-templates/${id}` as const,
  DETAIL_TEMPLATES: '/dashboard/detail-templates' as const,
  DETAIL_TEMPLATE_NEW: '/dashboard/detail-templates/new' as const,
  DETAIL_TEMPLATE_EDIT: (id: number | string) => `/dashboard/detail-templates/${id}` as const,
  // 🔴 매출·정산 화면 (FEATURE_2609_30). 위 SALES_PRODUCTS_* 는 '판매상품 관리'라 이름만 비슷하고
  // 전혀 다른 화면이다 — 새 항목에 SALES_PRODUCTS_ 접두사를 재사용하지 말 것.
  SALES_SUMMARY: '/dashboard/sales/summary' as const,
  SALES_BY_PRODUCT: '/dashboard/sales/products' as const,
  SETTLEMENT_PAYOUTS: '/dashboard/sales/settlement' as const,
  SETTLEMENT_PAYOUT_DETAIL: (id: number | string) => `/dashboard/sales/settlement/${id}` as const,
  PROCESSING_PRESETS: '/dashboard/processing-presets' as const,
  PROCESSING_PRESET_NEW: '/dashboard/processing-presets/new' as const,
  PROCESSING_PRESET_EDIT: (id: number | string) => `/dashboard/processing-presets/${id}` as const,
} as const;
