export const ROUTES = {
  ROOT: '/',
  LOGIN: '/login',
  DASHBOARD: '/dashboard',
  REGISTER: '/register',
  PRODUCTS_RETRIEVE: '/dashboard/products/retrieve',
  PRODUCTS_REGISTER: '/dashboard/products/register',
  PRODUCT_DETAIL: (id: number | string) => `/dashboard/products/${id}`,
  PRODUCT_EDIT: (id: number | string) => `/dashboard/products/${id}?mode=edit`,
  STOCK_IN_OUT: '/dashboard/stock/in-out',
  STOCK_OUTBOUND: '/dashboard/stock/outbound',
  STOCK_PACKING: '/dashboard/stock/packing',
  STOCK_SEARCH: '/dashboard/stock/search',
  USER_REGISTER: '/dashboard/users/register',
  USER_MANAGE: '/dashboard/users/manage',
  COSTS_CARRIER: '/dashboard/costs/carrier',
  COSTS_CARRIER_COMPANY: '/dashboard/costs/carrier-company',
  COSTS_PACKAGE: '/dashboard/costs/package',
  COSTS_CATEGORY: '/dashboard/costs/category',
  COSTS_COMMISSION_RATE: '/dashboard/costs/commission-rate',
  COSTS_FIXED_COST: '/dashboard/costs/fixed-cost',
  SALES_PRODUCTS_RETRIEVE: '/dashboard/sales-products/retrieve' as const,
  SALES_PRODUCTS_RETRIEVE_DETAILS: (id: number | string) => `/dashboard/sales-products/retrieve/${id}` as const,
  SALES_PRODUCTS_RETRIEVE_EDIT: (id: number | string) => `/dashboard/sales-products/retrieve/${id}/edit` as const,
  MASTER_PRODUCTS: '/dashboard/master-products' as const,
  MASTER_PRODUCT_NEW: '/dashboard/master-products/new' as const,
  // 2609_45/D17: 경로·메뉴 라벨 모두 플랫폼 중립. 플랫폼 이름은 화면의 `PLATFORMS` 표에서만 나온다.
  MASTER_PRODUCT_NEW_FROM_CHANNEL: '/dashboard/master-products/new-from-channel' as const,
  MASTER_PRODUCT_DETAIL: (id: number | string) => `/dashboard/master-products/${id}` as const,
  MASTER_PRODUCT_DETAIL_EDIT: (masterId: number | string, listingId: number | string) =>
    `/dashboard/master-products/${masterId}/detail/${listingId}` as const,
  // 2609_64/D9: 구성상품 변경은 팝업이 아니라 페이지다(검색·선택 + 옵션×구성상품 수량 격자 = 긴 작업).
  MASTER_PRODUCT_COMPOSITION: (id: number | string) =>
    `/dashboard/master-products/${id}/composition` as const,
  MARGIN_POLICIES: '/dashboard/margin-policies' as const,
  LISTINGS_SYNC: '/dashboard/listings/sync' as const,
  // 🔴 LISTINGS_SYNC(콘텐츠 재전송·재심사) 와 다른 화면이다 — 이쪽은 가격 전송(FEATURE_2609_39 / PLAN D12).
  LISTINGS_REPRICING: '/dashboard/listings/repricing' as const,
  SELLERS_LIST: '/dashboard/sellers/list' as const,
  SELLERS_MANAGE: '/dashboard/sellers/manage' as const,
  ORDERS_RETRIEVE: '/dashboard/orders' as const,
  ORDERS_SHIPMENT: '/dashboard/orders/shipment' as const,
  ORDERS_CLAIMS: '/dashboard/orders/claims' as const,
  ORDERS_INQUIRIES: '/dashboard/orders/inquiries' as const,
  // 🔴 사이드바 메뉴가 아니다(FEATURE_2609_51 / D13) — 진입은 상단 종 말풍선 하단 [전체 보기] 하나뿐이다.
  ALERTS: '/dashboard/alerts' as const,
  PURCHASE_LIST: '/dashboard/purchase/list' as const,
  SETTINGS_LOGGING: '/dashboard/settings/logging' as const,
  THUMBNAIL_TEMPLATES: '/dashboard/thumbnail-templates' as const,
  THUMBNAIL_TEMPLATE_NEW: '/dashboard/thumbnail-templates/new' as const,
  THUMBNAIL_TEMPLATE_EDIT: (id: number | string) => `/dashboard/thumbnail-templates/${id}` as const,
  DETAIL_TEMPLATES: '/dashboard/detail-templates' as const,
  DETAIL_TEMPLATE_NEW: '/dashboard/detail-templates/new' as const,
  DETAIL_TEMPLATE_EDIT: (id: number | string) => `/dashboard/detail-templates/${id}` as const,
  // 🔴 매출·정산 화면 (FEATURE_2609_30). 위 SALES_PRODUCTS_* 는 '판매상품 관리'라 이름만 비슷하고
  // 전혀 다른 화면이다 — 새 항목에 SALES_PRODUCTS_ 접두사를 재사용하지 말 것.
  SALES_SUMMARY: '/dashboard/sales/summary' as const,
  SALES_BY_CHANNEL: '/dashboard/sales/channels' as const,
  SALES_BY_PRODUCT: '/dashboard/sales/products' as const,
  SETTLEMENT_PAYOUTS: '/dashboard/sales/settlement' as const,
  SETTLEMENT_PAYOUT_DETAIL: (id: number | string) => `/dashboard/sales/settlement/${id}` as const,
  PROCESSING_PRESETS: '/dashboard/processing-presets' as const,
  PROCESSING_PRESET_NEW: '/dashboard/processing-presets/new' as const,
  PROCESSING_PRESET_EDIT: (id: number | string) => `/dashboard/processing-presets/${id}` as const,
} as const;
