export const ROUTES = {
  ROOT: '/',
  LOGIN: '/login',
  DASHBOARD: '/dashboard',
  REGISTER: '/register',
  PRODUCTS_RETRIEVE: '/dashboard/products/retrieve',
  PRODUCTS_REGISTER: '/dashboard/products/register',
  PRODUCT_DETAIL: (id: number | string) => `/dashboard/products/${id}`,
  PRODUCT_EDIT: (id: number | string) => `/dashboard/products/${id}?mode=edit`,
  STOCK_IN_OUT: '/dashboard/stock/in-out',
  STOCK_SEARCH: '/dashboard/stock/search',
  USER_REGISTER: '/dashboard/users/register',
  USER_MANAGE: '/dashboard/users/manage',
  COSTS_CARRIER: '/dashboard/costs/carrier',
  COSTS_CARRIER_COMPANY: '/dashboard/costs/carrier-company',
  COSTS_PACKAGE: '/dashboard/costs/package',
  COSTS_CATEGORY: '/dashboard/costs/category',
  COSTS_COMMISSION_RATE: '/dashboard/costs/commission-rate',
  SALES_PRODUCTS_REGISTER: '/dashboard/sales-products/register' as const,
  SALES_PRODUCTS_RETRIEVE: '/dashboard/sales-products/retrieve' as const,
  SALES_PRODUCTS_RETRIEVE_DETAILS: (id: number | string) => `/dashboard/sales-products/retrieve/${id}` as const,
  SALES_PRODUCTS_RETRIEVE_EDIT: (id: number | string) => `/dashboard/sales-products/retrieve/${id}/edit` as const,
  MASTER_PRODUCTS: '/dashboard/master-products' as const,
  MASTER_PRODUCT_DETAIL: (id: number | string) => `/dashboard/master-products/${id}` as const,
  MARGIN_POLICIES: '/dashboard/margin-policies' as const,
  LISTINGS_SYNC: '/dashboard/listings/sync' as const,
  SELLERS_LIST: '/dashboard/sellers/list' as const,
  SELLERS_MANAGE: '/dashboard/sellers/manage' as const,
  ORDERS_RETRIEVE: '/dashboard/orders' as const,
  PURCHASE_LIST: '/dashboard/purchase/list' as const,
  SETTINGS_LOGGING: '/dashboard/settings/logging' as const,
  THUMBNAIL_TEMPLATES: '/dashboard/thumbnail-templates' as const,
  THUMBNAIL_TEMPLATE_NEW: '/dashboard/thumbnail-templates/new' as const,
  THUMBNAIL_TEMPLATE_EDIT: (id: number | string) => `/dashboard/thumbnail-templates/${id}` as const,
} as const;
